name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'sequence/package-lock.json'  # Ensure correct path

      - name: Move to correct directory
        run: cd sequence && ls -la  # Check if package-lock.json exists

      - name: Install dependencies
        run: cd sequence && npm install  # Manually switch to sequence folder

      - name: Build
        run: cd sequence && npm run build  # Build inside the correct folder

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'sequence/dist'  # Ensure correct path to build output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
