name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'sequence/package-lock.json'  # Specify the correct path

      - name: Install dependencies
        run: npm install
        working-directory: sequence  # Specify the working directory

      - name: Build
        run: npm run build
        working-directory: sequence  # Specify the working directory

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './sequence/dist'  # Make sure this is the correct build output path

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
